### PR TITLE
Improve index page

### PR DESCRIPTION
**Pull request by jonasvag**
Improve index page

### CODE REVIEW

**Comment by jonasvag** [comment]
Hello, anything needs to be improved further here?

**Comment by Octet3290** [comment]
> Hello, anything needs to be improved further here?

Hey, Thanks for your pull request but your changes seems to throw error so kindly go through your changes again.

**Comment by jonasvag** [comment]
Hello, what error? Do you have a screenshot?

**Comment by Octet3290** [comment]
> Hello, what error? Do you have a screenshot?

Wait let me show you. But first let me know what kind of changes you expect if i run your code.

**Comment by jonasvag** [comment]
Some small changes: details text in white color; added website title visible on the tab; logging for connect button trigger; link to google chrome; information about supported test network Goerli.

https://github.com/Octet3290/NFT-Blockchain/pull/2/files 
image
All of this to celebrate Hacktoberfest 2022 :)

**Pull request closed without merging**
